spring.application.name=backend
server.port=8082


# Perfil (memory, mongo, postgres), incluye el selector de almacenamiento aqui
spring.profiles.active=postgres
# Selector de estrategia del motor (collections o custom)
app.tree-strategy=custom