spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/territorial_tree_db}
spring.mongodb.database=territorial_tree_db

app.storage=mongo

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.data.jpa.autoconfigure.JpaRepositoriesAutoConfiguration