spring.application.name=backend
server.port=8081

# Perfil (cambiar a postgres o mongo según la persistencia deseada)
spring.profiles.active=memory
# Selector de almacenamiento
app.storage=memory
# Selector de estrategia del motor (collections o custom)
app.tree-strategy=collections

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.data.jpa.autoconfigure.JpaRepositoriesAutoConfiguration