spring.application.name=backend
server.port=8082

# Perfil (memory, mongo, postgres), incluye el selector de almacenamiento aqui
spring.profiles.active=memory
# Selector de almacenamiento
app.storage=memory
# Selector de estrategia del motor (collections o custom)
app.tree-strategy=custom

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.data.jpa.autoconfigure.JpaRepositoriesAutoConfiguration