spring.data.mongodb.uri=mongodb://localhost:27017/territorial_tree_db
spring.data.mongodb.database=territorial_tree_db

app.storage=mongo
server.port=8081

# Reactivar JPA para que no interfiera (no se usa en este perfil)
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
  org.springframework.boot.data.jpa.autoconfigure.JpaRepositoriesAutoConfiguration